### ISSUE TITLE
AWS API endpoints research

### ISSUE THREAD

**Issue by Xerof47Vel** [COS301-SE-2024/Smart-Storage-Organizer-Application#2]

**Comment by Siyabonga-Mbuyisa-u20491621** [comment]
Victor am considering that we use the Amplify Rest API . It more doable and  with time constraint. But there other implication of using Amplify Rest API.  We must talk about this in the meeting

**Comment by Siyabonga-Mbuyisa-u20491621** [comment]
The research has been done. and API works
