### ISSUE TITLE
Database User Table

### ISSUE THREAD

**Issue by Siyabonga-Mbuyisa-u20491621** [COS301-SE-2024/Smart-Storage-Organizer-Application#3]
Create User Table With the following attributes
UserID- INT(8) 
Name - VARCHAR(255)
Surname - VARCHAR(255)
Email- VARCHAR(255)
Logined- VARCHAR(255)
LastLogin - DateTime
Role - VARCHAR(255)
Authenticated - BOOLEAN
Password -VARCHAR(255)

**Comment by Siyabonga-Mbuyisa-u20491621** [comment]
A user table has created but does not contain all these attributes. It contain (Email, Name , Surname, Address, Cell Number)
Note this user table is created inside amplify for access control
Hence a Profile Table.   Tshegofatso you have the attributes

**Comment by Siyabonga-Mbuyisa-u20491621** [comment]
We were able to use Amplify Auth to store user data.

**Comment by TshegofatsoMapheto** [comment]
1 hour

**Comment by TshegofatsoMapheto** [comment]
Done
